name: drought
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base = 4.13
  - r-tidyverse = 4.5.2
  - r-markdown = 2.0
  - m2-wget = 1.25.01
  - snakemake==9.14.5
  - graphviz=14.1.0
  - coreutils=8.32.5
  - r-showtext = 0.9_7
  - imagemagick = 7.1.0